DROP TABLE IF EXISTS customContent;
CREATE TABLE customContent (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  inputs TEXT NULL,
  content TEXT NULL,
  PRIMARY KEY(id)
)ENGINE=MyIsam DEFAULT CHARSET=UTF8;
