<h2 class="title">Astrology: The 11th House and True Humanism</h2>
<div class="social_networks"></div>
<img class="article_image" src="img/articles_miniatures/acuario.jpg" alt="Illustration of Aquarius"></img>
<?php include('social-networks.php'); ?>

<div>
  <p>In this article, we will explore the topic of <strong>astrological houses</strong>, specifically focusing on the <strong>eleventh house</strong>. Let's recall what houses are in a natal chart: they are <strong>fields of experience</strong>, the <strong>stages</strong> of life, embodying twelve <strong>archetypes</strong> of human experience.</p>
  <p>Some astrologers have often associated <strong>all creative processes</strong> with the <strong>fifth house</strong>. However, in this house, the individual creates on a personal level, alone, or as the head of a household. It is creativity in a more specific field.</p>
  <p>On the other hand, in the eleventh house, "wholeness" creates through the individual. It is not from him but <strong>through him</strong> that the process takes place. This implies that it <strong>transcends</strong> and can reach humanity as a <strong>whole</strong>, as a community. It is an action <strong>without</strong> <strong>personal interest</strong>; that is the key to a truly creative and free action.</p>
  <p>Experiences in the eleventh house involve externalizing the <strong>ideals</strong> of a person in relation to those who <strong>share</strong> these ideals, which is why it is known as the house of <strong>&ldquo;friends&rdquo;</strong>.</p>
  <p>The symbolism of this house is related to the sign of <strong>Aquarius</strong>, <strong>humanistic and idealistic</strong>, and the planet <strong>Uranus, described as a illuminating ray</strong> that breaks old structures to act at the forefront, with a <strong>transcendent</strong> purpose.</p>
  <p>Houses follow each other as part of a <strong>learning process</strong>, they are not isolated. This house is followed by the <strong>twelfth, the last house</strong> before a <strong>new</strong> beginning in an experience, as in the <strong>first house</strong>. What is full must be <strong>emptied</strong> before starting another stage of <strong>growth</strong>.</p>
  <p>But the <strong>deepest process</strong> is always, symbolically speaking, to transform a <strong>repetitive circle into a spiral</strong>, where there is the possibility to leave the known and move towards <strong>the transcendent, our true destiny</strong>.</p>
  <p><strong>Today we are facing a unique opportunity, in a very special historical moment to achieve these changes: &ldquo;The Age of Aquarius&rdquo;. The world is transforming, and with it, our way of living, loving, connecting with each other, and with the entire cosmos.</strong></p>
  <p><strong>Marilyn Ferguson describes it in her popular book:</strong> &ldquo;The Aquarian Conspiracy is a different form of revolution, with a <strong>new type of revolutionaries</strong>. What it seeks is a <strong>change</strong> in <strong>consciousness</strong> in a critical number of individuals, enough to <strong>precipitate the renewal</strong> of <strong>the entire society</strong>. <strong>We cannot wait for the world to change</strong>, nor for new times to make us change, nor wait for the revolution to come and sweep us into its new race. <strong>The future is ourselves. We are the revolution.&rdquo;</strong></p>
  <p>Source: Book &ldquo;The Astrological Houses&rdquo; by Dane Rudhyar.</p>
</div>
