<h2 class="title">Astrología: La casa 11 y el Verdadero Humanismo</h2>
<div class="social_networks"></div>
<img class="article_image" src="img/articles_miniatures/acuario.jpg"></img>
<?php include('social-networks.php'); ?>

<div>
  <p>En este artículo vamos a ver el tema de las <strong>casas astrológicas</strong>, en particular sobre la <strong>casa once</strong>. Recordemos <strong>qué </strong>son las casas en una carta natal: son <strong>campos de la experiencia</strong>, los <strong>escenarios</strong> de la vida, hay doce <strong>arquetipos</strong> de la experiencia humana.</p>
  <p>Algunos astrólogos han identificado a menudo a <strong>todos</strong> los <strong>procesos creativos</strong> con la <strong>casa quinta</strong>. Pero en esta casa está el individuo que crea en lo personal, solo o como jefe de hogar. Es lo creativo en un campo más particular..</p>
  <p>En cambio, es en la undécima casa donde &ldquo;la totalidad&rdquo; crea a través del individuo. No es desde él, sino <strong>a través suyo</strong>, que se realiza el proceso. Esto implica que lo <strong>trasciende</strong> y puede alcanzar a la humanidad como un <strong>todo</strong>, una comunidad. Es una acción<strong> sin</strong> <strong>interés personal</strong>, no busca llevarse los frutos; esa es la clave de una acción <strong>verdaderamente</strong> creadora y libre.</p>
  <p>Las experiencias de la casa once refieren a exteriorizar los <strong>ideales</strong> de un hombre, en relación con quienes <strong>comparten</strong> estos ideales, y por eso se la conoce como la casa de <strong>&ldquo;los amigos&rdquo;.</strong></p>
  <p>A su vez el simbolismo de esta casa guarda relación con el signo de <strong>Acuario,</strong> <strong>humanista e  idealista</strong>; y con el planeta <strong>Urano, se lo describe como un rayo que todo lo ilumina</strong> y que rompe con las <strong>viejas</strong> estructuras para obrar en la vanguardia, con un fin <strong>trascendente.</strong></p>
  <p>Las casas se suceden como parte de <strong>un proceso de aprendizaje</strong>, no están aisladas entre sí. Esta casa es seguida por <strong>la duodécima, la última casa </strong>antes de <strong>un nuevo </strong>comienzo en una experiencia de inicio como lo es la <strong>primera casa</strong>. Lo que está lleno debe <strong>vaciarse</strong>, antes de empezar otra etapa de <strong>crecimiento</strong>.</p>
  <p>Pero el <strong>proceso más profundo</strong> es siempre, simbólicamente hablando, el de transformar un<strong> círculo repetitivo en espiral, </strong>es donde está la posibilidad de dejar lo conocido  y avanzar hacia<strong> lo trascendente, nuestro verdadero destino.  </strong></p>
  <p><strong>Hoy estamos frente a una oportunidad única,  en un momento histórico muy especial para alcanzar estos cambios: &ldquo;La Era de Acuario&rdquo;. El mundo se transforma y con ello nuestra forma de vivir, amar, vincularnos entre nosotros y con todo el cosmos.</strong></p>
  <p><strong>Ya lo describe Marilyn Ferguson en su popular libro: &ldquo;</strong><strong>La Conspiración de Acuario</strong> es una forma distinta de revolución, con un <strong>nuevo tipo de revolucionarios</strong>. Lo que busca es <strong>un cambio</strong> de <strong>conciencia</strong> en un número crítico de individuos, lo suficiente como <strong>para precipitar la renovación</strong> de la <strong>sociedad entera</strong>. <strong>No podemos esperar hasta que el mundo cambie</strong>; ni hasta que vengan nuevos tiempos que nos hagan cambiar a nosotros, ni esperar que llegue la revolución y nos arrastre en su nueva carrera. <strong>El futuro somos nosotros mismos. Nosotros somos la revolución.»</strong></p>
  <p>Fuente: Libro &ldquo;Las Casas Astrológicas&rdquo; de Dane Rudhyar.</p>
</div>
