<h2 class="title">Aspectos J&uacute;piter/Neptuno</h2>
<div class="social_networks"></div>
<img class="article_image" src="img/articles_miniatures/aspectos-jupiter-neptuno.jpg"></img>
<?php include('social-networks.php'); ?>

<p>En astrolog&iacute;a, cada planeta en la <strong>carta natal</strong> marca m&uacute;ltiples significados. Nos marca un camino, una orientaci&oacute;n. En este caso tomamos el significado astrol&oacute;gico de los aspectos entre Neptuno y J&uacute;piter. Si ten&eacute;s este aspectos en tu carta natal la descripci&oacute;n a continuaci&oacute;n ser&aacute; indicada para vos, siempre y cuando la combinemos con <strong>toda</strong> la carta natal:</p>
<p><em>Una amplia y constante necesidad de experimentar la unidad con algo m&aacute;s grande que el propio yo individual y las pequeñas preocupaciones individuales. El nativo cree en la realidad del &aacute;mbito intangible de la experiencia, lo cual en ocasiones le conduce a una imaginaci&oacute;n hiperactiva y a un constante deseo de escapar, o bien a una inspiraci&oacute;n significativa.</em></p>
<p>Cuando se combinan los dos planetas m&aacute;s idealistas en la carta natal el resultado es un idealismo pujante, una amplia sensaci&oacute;n de las infinitas posibilidades que nos proporciona la vida. Esto puede llevar al individuo a convertirse en un idealista pr&aacute;ctico como en el caso de <em>Bertrand Russell </em>(cuadratura) o de <em>Albert Schweitzer</em> (oposici&oacute;n), en un artista como <em>Laurence Olivier</em>, actor y director brit&aacute;nico que ten&iacute;a conjunci&oacute;n, o en un escapista como el duque de Windsor quien abdic&oacute; en 1936 al trono de Inglaterra para casarse con Wallis Simpson. Otro ejemplo de este aspecto en la carta natal es Franklin D. Roosevelt, quien manifest&oacute; imaginaci&oacute;n en la resoluci&oacute;n de problemas pr&aacute;cticos (J&uacute;piter en conjunci&oacute;n Neptuno en Tauro) y adem&aacute;s se desempeñ&oacute; en su juventud como Secretario de Marina (Neptuno).</p>
<p>Al estudiar este aspecto veremos que nos indica que suelen tener una vida imaginativa y/o fantasiosa. Por ejemplo, <em>Joseph Kennedy</em> quien soñ&oacute; siempre con el poder y llegar a ser presidente, termin&oacute; instando a que su hijo se pudiera convertir en presidente de USA, pero su J&uacute;piter estaba en oposici&oacute;n a Neptuno y Plut&oacute;n lo cual indicaba una obsesi&oacute;n por el poder y adem&aacute;s ten&iacute;a J&uacute;piter conjunci&oacute;n Marte en Escorpio. Fue un influyente y poderoso inversor, empresario, diplom&aacute;tico y una figura pol&iacute;tica de los Estados Unidos, padre del <em>Presidente John F. Kennedy</em> y de los Senadores <em>Robert y Ted Kennedy</em>. Como uno de los l&iacute;deres del Partido Dem&oacute;crata, especialmente dentro de la comunidad cat&oacute;lica-irlandesa, y con negocios e intereses econ&oacute;micos por toda la naci&oacute;n, cre&oacute; la fortuna pol&iacute;tica y econ&oacute;mica de la Familia Kennedy.</p>
<p>Fascinante es descubrir que la gran imaginaci&oacute;n de Julio Verne est&aacute; apoyada por su Sextil J&uacute;piter-Neptuno. Al escritor no solo le encantaba navegar por los mares de Europa y &aacute;frica, Neptuno asociados con el Mar, sino que su novela &ldquo;Veinte mil leguas de viaje submarino&rdquo; se ha convertido en una de sus creaciones m&aacute;s perdurables. Es curioso que un campe&oacute;n ol&iacute;mpico de nataci&oacute;n como Mark Spitz naciera con J&uacute;piter tr&iacute;gono Neptuno-Marte. Fue un nadador estadounidense que consigui&oacute; siete medallas de oro en los Juegos Ol&iacute;mpicos de M&uacute;nich 1972, rompiendo marca mundial en cada uno de sus triunfos.</p>
<p>Esta combinaci&oacute;n tambi&eacute;n puede indicar una considerable intuici&oacute;n y talento como el de Joseph Campbell, que us&oacute; para expandir nuestro conocimiento de la literatura, la mitolog&iacute;a y la b&uacute;squeda personal de significado y trascendencia. Su J&uacute;piter en conjunci&oacute;n con el Sol y Mercurio, en cuadratura con Neptuno, se canaliz&oacute; en libros como &ldquo;El h&eacute;roe de las mil caras&rdquo; y &ldquo;Las m&aacute;scaras de Dios&rdquo;. Campbell, de Aries, ten&iacute;a Sol, Mercurio, J&uacute;piter y Marte en el mismo signo. La astrolog&iacute;a nos permite comprobar que el poeta T.S. Eliot que tambi&eacute;n contribuy&oacute; a revitalizar el inter&eacute;s por la mitolog&iacute;a, ten&iacute;a en su carta una oposici&oacute;n exacta entre J&uacute;piter y Neptuno. Eso explica la importancia del sentimiento religioso en su vida, que de modo espont&aacute;neo trasladar&iacute;a a su poes&iacute;a. Dicho trasvase se plasma a trav&eacute;s de la incorporaci&oacute;n, aqu&iacute; y all&aacute;, de innumerables citas tomadas de la Biblia, de obras de santos, del Dante, as&iacute; como de textos sagrados orientales.</p>
<p>En el peor de los casos estos aspectos en una carta natal pueden indicar ilusiones engañosas y autoengaños a nivel personal o ideol&oacute;gico. Pero en su mejor expresi&oacute;n se expresa como un compasivo amor por la humanidad y/o una apreciaci&oacute;n de sutilezas de orden m&iacute;stico o art&iacute;stico. Otro ejemplo de la uni&oacute;n J&uacute;piter-Neptuno es el monje y escritor Thomas Merton, cuyo quincunce exacto se manifest&oacute; en la forma de sus escritos espirituales, que fueron de inspiraci&oacute;n para sus lectores. Nacido en 1915 (m.1968) fue un monje trapense, poeta y pensador.</p>
