<h2 class="title">The Keys to Compatibility in Love and Astrology</h2>
<div class="social_networks"></div>
<img class="article_image" src="img/articles_miniatures/compatibilidad.jpg" alt="Compatibility in Love and Astrology"></img>
<?php include('social-networks.php'); ?>

<div>
  <p><strong>What factors determine the success or failure of a romantic relationship or marriage? Love remains, in part, a mystery for many. However, psychologist Carl Jung investigated how Astrology allows us to understand the "call of Cupid."</strong></p>
  <p>Carl Gustav <strong>Jung</strong>, one of the fathers of modern psychology, never lost his <strong>spirit of inquiry and scientific exploration</strong>. This allowed him to explore topics that, from the perspective of "official" psychiatry, were considered taboo or outright dismissed. He delved into <strong><a style="color: coral" href="http://aztlan.com.ar/blog/carl-gustav-jung/la-alquimia-jung-y-el-camino-al-ser-total.html" target="_blank">Alchemy</a>,</strong> <a style="color: coral" href="http://aztlan.com.ar/blog/sin-categoria/fisica-cuantica-y-psicologia.html" target="_blank"><strong>Quantum Physics</strong></a>, and also Astrology, among other subjects. His <strong>broad and prejudice-free mindset</strong> led to a strained relationship with Freud, who did not accept this broader view of knowledge and the human being.</p>
  <p>In his years of work, he observed that there was an <strong>invisible force</strong> determining <strong>attraction or rejection between individuals</strong>, and he decided to investigate it. Through a statistical experiment, he verified the relationship between <strong>Astrology</strong> and <strong><a style="color: coral" href="http://www.centroastrologico.com.ar/blog/astrologia-personal/la-astrologia-revela-la-compatibilidad-en-el-amor.html" target="_blank">romantic love</a></strong>.</p>
  <p>The relationship of astrology with the union of couples was documented in his book <strong>"On the Nature of the Psyche and Synchronicity."</strong> The book is dedicated to providing the foundations of Astrology, using a statistical experiment on <a style="color: coral" href="http://www.centroastrologico.com.ar/blog/astrologia-personal/que-es-la-carta-natal.html" target="_blank"><strong>natal charts</strong></a> of marriages. Gathering more than <strong>900 horoscopes of marriages</strong> for research, he analyzes the main points of <strong>Natal Chart Compatibility</strong>. Faced with <strong><a style="color: coral" href="http://www.centroastrologico.com.ar/blog/astrologia-personal/por-que-estudiar-astrologia-15-razones-para-estudiar-astrologia.html" target="_blank">prejudiced criticism</a></strong> against Astrology, Jung puts facts first and states that if we want <strong>scientific proof</strong> of Astrology, we need to use clearly observable and well-determined facts, such as the relationship between <strong><a style="color: coral" href="http://www.centroastrologico.com.ar/blog/astrologia-personal/la-astrologia-y-la-salud.html" target="_blank">diseases and astrology</a></strong> or the union of two people in a romantic relationship. Here are some excerpts from this book:</p>

<ul style="font-size:16px;">
  <li><em>"The mythological, traditional astrological, and alchemical correspondence (i.e., the theme of <strong>the nuptials of the sun and the moon in alchemy</strong>) is, from antiquity, <strong>the union of Sun-Moon, Moon-Moon, and Moon-Ascendant</strong>."</em></li>
  <li>Jung cites <strong>Ptolemy</strong>, who postulates <strong>3 degrees of harmony</strong> between factors in the horoscopes of men and women that indicate their attraction or rejection.</li>
  <li>Based on the study of alchemical tradition, he <strong>says:</strong> "Speaking in a general way, the <strong>common life</strong> of the couple will be <strong>long</strong> and constant when <strong>Sun</strong> and <strong>Moon</strong> are harmoniously constellated with each other." A classic example is the union of <strong>Goethe</strong> with Christina Vulpius, specifically his Sun in Virgo conjoined with her Moon.</li>
</ul>
<p>He then warns, with his usual scientific spirit, that to conduct such research, <strong>no FAITH</strong> in Astrology is necessary; only birth data is needed, and through <strong>astrological study</strong>, these <strong><a style="color: coral" href="http://www.centroastrologico.com.ar/blog/astrologia-personal/astrologia-moderna-aprende-tu-carta-natal.html" target="_blank">tendencies</a></strong> can be evaluated.</p>
<p>To contribute more data that confirms astrological influence, he provides a series of <strong>examples</strong> regarding the agreement between <strong>solar cycles</strong> and the <strong>mortality curve</strong>. Quoting Jung, "the <strong>increased activity</strong> of solar radiation produces <strong>disturbances</strong> in the Earth's magnetic field, and this <strong>affects</strong> the climate and the terrestrial environment as a whole, including <strong>humans</strong>. They also influence the ether of <strong>radio broadcasts</strong> by disturbing the ionosphere that reflects radio waves."</p>
</div>
