<h2 class="title">Compatibilidad de relación o Sinastrías</h2>
<div class="social_networks"></div>
<img class="article_image" src="img/articles_miniatures/compatibilidad-de-relacion-o-sinastrias.jpg"></img>
<?php include('social-networks.php'); ?>

<p>Permite clarificar los puntos de afinidad y conflicto de dos o más personas (relaciones de Pareja, Padres e Hijos, Sociedades, Selección De Personal Laboral y Otros).</p>

<p>El estudio de las relaciones entre dos personas se debe comenzar por una análisis completo de sus propias cartas natales. Esto significa conocer cuál es el tipo psicológico o tendencia predominante en cada uno de los dos integrantes de una relación. Si bien este tipo de informe es muy utilizado para Parejas, también el estudio puede hacerse para Sociedades comerciales, para padres e hijos, amistades, etc. Esto constituye algo muy importante ya que conocer con mayor profundidad al otro me ayudará a comprenderlo más y así acompañarlo. Básicamente, el trabajo se divide en 2 partes:
Permite clarificar los puntos de afinidad y conflicto de dos o más personas (relaciones de Pareja, Padres e Hijos, Sociedades, Selección De Personal Laboral y Otros).</p>

<p>El estudio de las relaciones entre dos personas se debe comenzar por una análisis completo de sus propias cartas natales. Esto significa conocer cuál es el tipo psicológico o tendencia predominante en cada uno de los dos integrantes de una relación. Si bien este tipo de informe es muy utilizado para Parejas, también el estudio puede hacerse para Sociedades comerciales, para padres e hijos, amistades, etc. Esto constituye algo muy importante ya que conocer con mayor profundidad al otro me ayudará a comprenderlo más y así acompañarlo. Básicamente, el trabajo se divide en 2 partes:</p>

<p>1. Estudio de las tendencias de cada uno de los individuos a la hora de re-lacionarse, enfocando las necesidades, deseos y orientaciones primor-diales de cada uno. ¿Qué es lo que se está buscando en la pareja? ¿Qué ideal predomina (siguiendo la idea de Jung de Anima – Animus, es decir el ideal de hombre para la mujer y el ideal de mujer para el hombre)?</p>

<p>2. ¿Cómo interactuarán los campos energéticos de las dos personas? ¿Cómo se ¨alimentarán¨ mutuamente estas dos personas? Especialmente, ello conlleva analizar el equilibrio de los elementos agua, fuego, tierra y aire en cada una de las dos cartas (esto muestra la energía, el tono global que se combina en la relación). ¿Qué tipo de impresión predomina? ¿Un buen equilibrio la mayoría de las veces? ¿Demasiado énfasis en la estimulación y excitación?¿Demasiado enfoque en la seguridad?¿Ambos poseen lo que el otro le falta, y si esto es así las parejas son demasiado diferentes, o pueden manejar las diferencias del otro e incluso apreciarlas?</p>

<p>Este análisis nos permitirá tener una idea de la complementariedad que existe entre las dos personas. Por ejemplo, dos personas fuego a fuego podrán ser especialmente creativas y productivas con mucha capacidad de invención y muy intensos, pero sin el equilibrio del resto de elementos, sus creaciones podrán resultar poco prácticas o perderse, necesitando el elemento tierra para equilibrar la pareja.</p>

<p>Esto no quiere decir que estén destinadas irrevocablemente a repetir estos patrones, sino que por el contrario al conocer cuales son los puntos fuertes y débiles de la relación se puede tener mayor libertad para identificarlos, modificarlos y trabajar sobre ellos. Todas las relaciones contienen un mayor o menor potencial para el crecimiento, ya que en algunos casos pueden reflejar aquellas zonas de nosotros mismos que requieren desarrollo y también pueden llevarnos a actuar de catalizadores respecto a áreas que otros deban atender especialmente. Es importante recalcar que la función de la sinastría no es emitir juicios rígidos respecto a la conveniencia de mantener una relación, sino resaltar las zonas de entendimiento y las desafiantes, para realzar las primeras y trabajar constructivamente las segundas, y también como guía para la toma de decisiones más conscientes.</p>

<p>Los Arquetipos de ANIMA, ANIMUS: según Jung</p>

<p>Carl Jung, el famoso psicólogo, habló del concepto de ANIMA Y ANIMUS: la imagen ideal, o arquetipo que la mujer tiene con respecto a de los hombres y todo lo masculino, y la que el hombre tiene de acerca de la mujer. La imagen ideal en parte es colectiva e histórica, es decir depende de la época. Por ejemplo en tiempos del Renacimiento la imagen de la mujer, lo que a los hombres los ¨inspiraba¨, las musas por ej., era muy diferente que la actual. Lo mismo en cuanto a la visión de lo masculino, que tenían las mujeres. Sin embargo, también hay tendencias personales, únicas, que están más allá de la época . Incluso a veces los valores de la época confunden a los individuos que terminan buscando su contraparte según las normas establecidas, modas, y no según sus íntimos anhelos. Estos anhelos muchas veces permanecen inconscientes desconocidos para nosotros mismos; la astrología permite hacerse consciente de nuestras profundas necesidades afectivas, aclarando la confusión.</p>

<p>Estos símbolos son extremadamente importantes cuando intentamos comprender lo que ocurre realmente en la interacción humana.</p>

<p>Relaciones kármicas:</p>

<p>Todas las relaciones contienen oportunidades para el crecimiento personal. Las relaciones nos aportan obstáculos y recompensas, nos hacen descender a lo más hondo y ascender a la cumbre, nos permiten la experiencia participativa personal que nos muestra qué hacemos realmente con nuestra filosofía de la vida cuando tenemos que poner en práctica lo que pensamos. Cuando el karma está implicado tendemos a experimentar una falta de control sobre las circunstancias y acontecimientos que suceden, así como una falta de control sobre la forma de reaccionar ante tales acontecimientos. Kármicamente, esas cualidades tienen que evolucionar si es que el individuo quiere crecer y estar más en contacto con su vida actual. La relación kármica adopta más el tono de cada individuo, quitando el velo de las ilusiones del otro. A través de este proceso se alcanza una nueva conciencia y, a medida que se alivia la carga del peso kármico, se puede experimentar una sensación de ligereza y libertad. Resulta interesante observar que el modelo kármico sólo suele ser comprendido con claridad después de haber aprendido una lección. Un individuo puede esforzarse por mantener una relación difícil durante meses o años, sin llegar a darse cuenta del sentido de su esfuerzo. La carga kármica sólo se disuelve después de que la dificultad haya salido a la luz y haya sido resuelta. La recompensa de esta dura tarea es la comprensión, que llega cuando cobramos conciencia del vínculo interconectado existente entre los residuos de la vida pasada y el ahora.</p>

<p>Si podemos aprender a alimentarnos unos a otros, en lugar de aferrarnos a nosotros mismos, incluso los aspectos más difíciles simbolizados en un horóscopo se convierten en parte del constante fluir de la corriente de la vida. Podemos aprovechar el karma, en lugar de dejarnos hundir por él. Las cargas, responsabilidades y obstáculos con que nos enfrentamos pueden, en último término, convertirse en el apoyo capaz de fortalecer un carácter en crecimiento permanente.</p>