<h2 class="title">Las claves de la compatibilidad en el amor y la Astrología</h2>
<div class="social_networks"></div>
<img class="article_image" src="img/articles_miniatures/compatibilidad.jpg"></img>
<?php include('social-networks.php'); ?>

<div>
  <p><strong>¿Qué factores determinan el éxito o fracaso de una relación de pareja o matrimonio? El Amor en parte sigue siendo un misterio para muchos, sin embargo fue el psicólogo Carl Jung quien investigara cómo la Astrología nos permite entender el “llamado de Cupido”.</strong>
  <p  >Carl Gustav <strong>Jung,</strong> uno de los padres de la Psicología moderna, nunca perdió su <strong>espíritu de investigador y científico</strong>. Esto le permitió explorar temas que desde el punto de vista de la psiquiatría “oficial” eran considerados tabú, o directamente desechados. Es así que se acercó a la <strong><a style="color: coral" href="http://aztlan.com.ar/blog/carl-gustav-jung/la-alquimia-jung-y-el-camino-al-ser-total.html" target="_blank">Alquimia</a>,</strong> la <a style="color: coral" href="http://aztlan.com.ar/blog/sin-categoria/fisica-cuantica-y-psicologia.html" target="_blank"><strong>Física Cuántica</strong></a> y también a la Astrología, entre otros temas. Su <strong>mentalidad amplia y libre de todo prejuicio le</strong> <strong>valió su relación con Freud</strong>, quien no aceptaba esta mirada más amplia del conocimiento y del ser humano.</p>
<p  >En sus años de trabajo, observó que había una <strong>fuerza invisible</strong> que determina la <strong>atracción o rechazo entre las personas</strong> y se decidió a investigarlo. Mediante un experimento estadístico, verificó la relación entre la <strong>Astrología</strong> y el <strong><a style="color: coral" href="http://www.centroastrologico.com.ar/blog/astrologia-personal/la-astrologia-revela-la-compatibilidad-en-el-amor.html" target="_blank">amor de pareja</a>.</strong></p>
<p  >La relación de la astrología con la unión de pareja quedó documentada en su libro <strong>“Sobre la Naturaleza de la Psique y la Sincronicidad</strong>”. El libro está dedicado a dar fundamentos de la Astrología, usando un experimento estadístico sobre<a style="color: coral" href="http://www.centroastrologico.com.ar/blog/astrologia-personal/que-es-la-carta-natal.html" target="_blank">cartas natales</a> de matrimonios. Reuniendo a modo de investigación una cantidad de más de <strong>900 horóscopos de matrimonios</strong> analiza los principales puntos de la <strong>Compatibilidad de Cartas natales</strong>. Frente a la <strong><a style="color: coral" href="http://www.centroastrologico.com.ar/blog/astrologia-personal/por-que-estudiar-astrologia-15-razones-para-estudiar-astrologia.html" target="_blank">crítica prejuiciosa</a></strong> hacia la Astrología, Jung antepone los hechos y dice que si queremos <strong>demostraciones científicas</strong> de la <strong>Astrología</strong> es necesario usar hechos claramente observables y bien determinados como la relación entre <strong ><a style="color: coral" href="http://www.centroastrologico.com.ar/blog/astrologia-personal/la-astrologia-y-la-salud.html" target="_blank">enfermedades y la astrología</a></strong>, o bien el caso de la <strong>UNION</strong> de pareja entre dos personas. He aquí algunos fragmentos de este libro:</p>

<ul style="font-size:16px;"  >
 	<li><em>“La correspondencia mitológica, la astrológica tradicional y la alquimista (es decir, el tema de <strong>las nupcias del sol y la luna en la alquimia</strong>) es desde la antigüedad, <strong>la unión Sol-Luna , Luna-Luna, y Luna-Ascendente</strong>.”</em></li>
 	<li>Jung cita a <strong>Ptolomeo</strong> quien postula <strong>3 grados de armonía</strong> entre factores de los horóscopos del hombre y la mujer que indican su atracción o rechazo.</li>
 	<li>Basándose en <strong>el estudio</strong> de la tradición alquimista <strong>dice:</strong> “Hablando de un modo general la <strong>vida en común</strong> de la pareja será <strong>larga</strong> y constante cuando <strong>Sol</strong> y <strong>Luna</strong> están consteladas <strong>armoniosamente</strong> entre sí”. Un ejemplo clásico es la unión de <strong>Goethe</strong> con Cristina Vulpius, a saber <strong>Sol</strong> de él en Virgo conjunción la <strong>Luna</strong> de ella”.</li>
</ul>
<p  >Advierte luego, con su habitual espíritu científico, que para realizar semejante investigación no es necesaria <strong>ninguna FE</strong> en la Astrología, sino solo tener los datos de nacimiento, y mediante el <strong>estudio astrológico</strong> evaluar estas <strong><a style="color: coral" href="http://www.centroastrologico.com.ar/blog/astrologia-personal/astrologia-moderna-aprende-tu-carta-natal.html" target="_blank">tendencias</a>.</strong></p>
<p  >A fin de aportar mayores datos que comprueban la influencia astrológica da una serie de <strong>ejemplos</strong> acerca de la concordancia entre los ciclos de <strong>manchas solares</strong> y la curva de <strong>mortalidad.</strong> Citándolo a Jung “la <strong>actividad aumentada</strong> de la radiación solar produce <strong>perturbaciones</strong> en el <strong>campo magnético</strong> de la tierra, y esto <strong>afecta</strong> al clima, y el medio ambiente terrestre en su totalidad, incluido el <strong>Ser humano.</strong> También influyen sobre el éter de las <strong>transmisiones</strong> radiales al perturbar la ionósfera que refleja las ondas radiales.”</p>

</div>
