<h2 class="title">Quien Soy, De Dónde Vengo y Hacia Dónde Voy</h2>
<div class="social_networks"></div>
<img class="article_image" src="img/articles_miniatures/destino.jpg"></img>
<?php include('social-networks.php'); ?>

<p><strong>Las Casas de Fuego.</strong></p>
<div>
  <p>Las <strong>casas</strong> astrológicas son los escenarios donde las energías astrológicas montan sus pequeñas obras con el fin de enseñarnos en la escuela de la vida a ser mejores seres humanos, son, como diría <strong>Stephen Arroyo</strong>, los campos de la experiencia.</p>
  <p>Las casas tienen una estrecha relación con el zodíaco, o sea, podríamos decir que tienen un funcionamiento análogo con los signos. Esto sería que comparten gran cantidad de similitudes, pero no por eso son iguales. Funcionan con el mismo tipo de energía pero se expresan de forma diferente.</p>
  <p>Si usamos la división de los elementos, vemos que los signos de fuego son Aries, Leo y Sagitario, y si lo transpolamos a las casa, veríamos que se relacionan con la I, la V y la IX, y si cambiamos la palabra <strong>fuego</strong> por <strong>identidad</strong>, vemos como estos, son los lugares donde se va a <strong>desarrollar</strong> ese <strong>aprendizaje.</strong></p>
  <p><img style="margin-right: 20px" src="http://www.centroastrologico.com.ar/blog/wp-content/uploads/2016/01/Cruze-de-caminos1-300x226.jpg" alt="" width="300" height="226" srcset="http://www.centroastrologico.com.ar/blog/wp-content/uploads/2016/01/Cruze-de-caminos1-300x226.jpg 300w, http://www.centroastrologico.com.ar/blog/wp-content/uploads/2016/01/Cruze-de-caminos1.jpg 400w" sizes="(max-width: 300px) 100vw, 300px">La <strong>Casa 1</strong> que es la relacionada a <strong>Aries</strong>, es la que nos marca la personalidad, al cuerpo físico, aunque no hay que confundirla con el ascendente, este se encuentra en esta casa, pero no son lo mismo, este porción de 30 grados da indicaciones precisas con relación al campo principal de acción del ser humano y cuanto éste considere para si. Todo planeta alli es muy significativo ya que constituyen la oportunidad de la acción concreta, la actuación en los asuntos reales. Tiene que ver con la <strong>identidad en acción</strong>, y a partir de ese accionar se va generando la posibilidad de generar <strong>experiencias para el crecimiento</strong>.</p>
  <p>La <strong>Casa V</strong> es la casa de <strong>la expresión de la identidad</strong>, tomando como palabra principal, la creatividad, lo cual es una palabra que hoy día le damos una connotación plenamente artística, pero se la ve también plasmada en la idea de los hijos, como creación, ya que la descendencia es la más importante creación de los seres humanos. Los planetas en esta casa señalan la actitud afectiva, tambien señalan la capacidad de hacer y el reconocimiento logrado por ello.</p>
  <p>Finalmente la última de esta tríada es la<strong> casa 9</strong>, relacionada al centauro, conocida como la casa de <strong>la posible evolución</strong>, en esta están representados los medios para alcanzar metas espirituales, los estudios superiores y los viajes largos, son los dos expresiones de la búsqueda de cultura, representa, el arte , la ciencia, la filosofía y la religión, que son los 4 caminos de conocimiento que representa sagitario en sus reflexiones que amplían horizontes.</p>
  <p>Planetas en estos sectores de la carta natal nos va a llevar a generar muchas cosas en lo externo pero siempre desde nosotros mismos como punto de partida, de afuera, se ve algo egoísta, pero poner a prueba la identidad nos va a llevar a reafirmarnos y a encontrarnos con quien realmente somos, ya que para estas casas nuestros actos van a reflejar quienes somos mas allá de nuestras fantasías.</p>
</div>
