<h2 class="title">Who I Am, Where I Come From, and Where I'm Going</h2>
<div class="social_networks"></div>
<img class="article_image" src="img/articles_miniatures/destino.jpg" alt="Illustration of Destiny"></img>
<?php include('social-networks.php'); ?>

<p><strong>The Houses of Fire.</strong></p>
<div>
  <p>Astrological <strong>houses</strong> are the stages where astrological energies set up their small plays to teach us in the school of life to be better human beings; they are, as <strong>Stephen Arroyo</strong> would say, the fields of experience.</p>
  <p>The houses have a close relationship with the zodiac, meaning we could say they function analogously to the signs. This would be that they share a lot of similarities, but they are not the same. They operate with the same type of energy but express themselves differently.</p>
  <p>If we use the division of elements, we see that the fire signs are Aries, Leo, and Sagittarius. If we extrapolate this to the houses, we see that they are related to the I, V, and IX; if we change the word <strong>fire</strong> to <strong>identity</strong>, we see how these are the places where this <strong>learning</strong> will <strong>develop.</strong></p>
  <p><img style="margin-right: 20px" src="http://www.centroastrologico.com.ar/blog/wp-content/uploads/2016/01/Cruze-de-caminos1-300x226.jpg" alt="" width="300" height="226" srcset="http://www.centroastrologico.com.ar/blog/wp-content/uploads/2016/01/Cruze-de-caminos1-300x226.jpg 300w, http://www.centroastrologico.com.ar/blog/wp-content/uploads/2016/01/Cruze-de-caminos1.jpg 400w" sizes="(max-width: 300px) 100vw, 300px">The <strong>1st House</strong>, related to <strong>Aries</strong>, marks our personality, the physical body. Although it should not be confused with the ascendant, which is in this house, they are not the same. This portion of 30 degrees provides precise indications regarding the main field of action of the human being and how much they consider for themselves. Every planet here is very significant as they constitute the opportunity for concrete action, performance in real matters. It is related to <strong>identity in action</strong>, and from that action, the possibility of generating <strong>experiences for growth</strong> arises.</p>
  <p>The <strong>5th House</strong> is the house of <strong>expression of identity</strong>, taking creativity as its main word, which is a word that today we give a purely artistic connotation, but it is also seen in the idea of children, as creation, since offspring is the most important creation of human beings. Planets in this house indicate the affective attitude; they also indicate the ability to do and the recognition achieved for it.</p>
  <p>Finally, the last of this triad is the <strong>9th house</strong>, related to the centaur, known as the house of <strong>possible evolution</strong>. Here, the means to achieve spiritual goals are represented, including higher education and long journeys. It embodies the two expressions of the quest for culture, representing art, science, philosophy, and religion, which are the four paths of knowledge that Sagittarius reflects in its reflections that broaden horizons.</p>
  <p>Planets in these sectors of the natal chart will lead us to generate many things externally but always from ourselves as a starting point. From the outside, it may seem selfish, but putting our identity to the test will lead us to reaffirm ourselves and to find out who we really are. For these houses, our actions will reflect who we are beyond our fantasies.</p>
</div>
