<h2 class="title">Destino o libre albedr&iacute;o</h2>
<div class="social_networks"></div>
<img class="article_image" src="img/articles_miniatures/destino-o-libre-albedrio.jpg"></img>
<?php include('social-networks.php'); ?>

<p>A lo largo de la historia, la Filosof&iacute;a se ha ocupado del profundo tema del destino del hombre y de su libertad. Seg&uacute;n Eur&iacute;pides (poeta griego): &ldquo;El destino domina sobre los dioses y sobre nosotros también&rdquo;.</p>
<p>Sin embargo en nuestra época actual, especialmente desde hace dos siglos atr&aacute;s, cuando irrumpe el auge del materialismo, la palabra Destino resulta controvertida y hasta ofensiva para muchas personas. Hoy en d&iacute;a mencionar Destino parece implicar una pérdida de control, una sensaci&oacute;n de desamparo o impotencia. De hecho, se hace demasiado énfasis en la idea de que somos libres de elecci&oacute;n hasta el extremismo. Pero… por otro lado, cuando uno busca que le ¨lean el futuro¨, ¿acaso no est&aacute; dando por hecho que est&aacute; todo escrito y previamente determinado?</p>
<p>Sin embargo, ¿Por qué tendemos tan f&aacute;cilmente a los extremos? Nos perdemos de ver los matices de la Relaci&oacute;n Destino - Libre albedr&iacute;o. Jeff Mayo, astr&oacute;logo inglés, afirma:</p>
<p>¨Usted puede pensar que si el futuro puede ser predicho no existe el libre albedr&iacute;o y estamos inmersos en un destino irrevocable del que no podemos escapar. El astr&oacute;logo no puede predecir todo acontecimiento…Un aspecto astrol&oacute;gico del futuro puede tener que ver con una variedad de posibilidades, la mayor parte de las cuales dependen de la ¨libertad de elecci&oacute;n¨ del individuo en concreto. Aunque el aspecto s&iacute; predice la tendencia actual de las circunstancias, o la naturaleza de la reacci&oacute;n individual a la situaci&oacute;n.¨</p>
<p>Osea que desde el punto de vista Astrol&oacute;gico hablamos de una relaci&oacute;n de interacci&oacute;n e interpenetraci&oacute;n entre Destino y libre albedr&iacute;o. Analicemos m&aacute;s en profundidad la idea del libre albedr&iacute;o, esta no es tan absoluta como afirma el materialismo, de hecho hay concretas circunstancias de la vida que me determinan y no elijo, como por ejemplo el lugar y momento de mi nacimiento entre otras tantas cosas. Es decir que hay algo que viene dado y que me determina. Pero, si todo est&aacute; destinado, ¿qué valor tiene lo que yo haga o pudiera hacer? La Astrolog&iacute;a Psicol&oacute;gica o Humanista considera que el destino de los individuos no es irrevocable. De hecho la Astrolog&iacute;a puede servir para advertir situaciones antes de que estas se manifiesten. Es decir que con Consciencia y Conocimiento puedo intervenir en mi Destino. Einstein a este respecto dijo:</p>
<p>¨Todo est&aacute; determinado, tanto el principio como el fin, por fuerzas sobre las cuales no tenemos ning&uacute;n control. Est&aacute; determinado para los insectos as&iacute; como para las estrellas. Seres humanos, vegetales, o polvo c&oacute;smico, todos bailamos al son de una tonada misteriosa entonada en la distancia por un intérprete invisible¨.</p>
<p>Por otro lado, la F&iacute;sica Cu&aacute;ntica, sostiene que no hay tantas certezas como probabilidades. Bajo este esquema el hombre tiene el potencial en latencia de escoger, porque la realidad se est&aacute; creando constantemente. Tenemos la posibilidad de hacer uso de nuestra capacidad de ser Co-Creadores de nuestra realidad. Para lograr esa libertad es necesario ampliar los conocimientos y la consciencia para usar nuestro Potencial Creativo, de lo contrario estaremos determinados por prejuicios; por el condicionamiento social o familiar recibido; y por nuestros h&aacute;bitos.</p>
<p>En las tradiciones orientales, por ejemplo, no se habla de destino sino de Karma. Karma es una palabra s&aacute;nscrita que significa acci&oacute;n. Originalmente se emple&oacute; en el contexto de la filosof&iacute;a Vedanta de la India. La idea es muy sencilla: cosechar&aacute;s lo que t&uacute; siembres. La Ley de Karma, es la ley de retribuci&oacute;n que dice que por cada acto habr&aacute; una reacci&oacute;n o efecto correspondiente. Cada individuo posee un determinado Karma, un destino personal, que no es arbitrario. Cada uno trae consigo un aprendizaje,un bagaje personal… pero éste a la vez puede ser modificado, perfeccionado a través de la experiencia y del Conocimiento de s&iacute; mismo.</p>
<p>En definitiva, tanto la F&iacute;sica Cu&aacute;ntica como el Budismo consideran que: quien tiene m&aacute;s conocimiento, tiene m&aacute;s libertad de acci&oacute;n que quien no lo tiene. Pongamos un simple ejemplo: Un gu&iacute;a de montaña es m&aacute;s libre al estar all&iacute; que un turista desorientado. El primero sabr&aacute; por qué lugares moverse y cu&aacute;les ser&aacute;n peligrosos, conocer&aacute; d&oacute;nde conseguir refugio y alimento, c&oacute;mo llegar y salir del lugar, etc. El Gu&iacute;a es evidentemente mucho m&aacute;s libre que el turista que desconoce todo eso. An&aacute;logamente sucede lo mismo en todos los campos de la vida.</p>
<p>La carta natal es un mapa del Karma o Destino personal. A través del estudio astrol&oacute;gico conoceré mis aptitudes y los principales escollos a sortear en mi vida. Al ponerme en mayor conocimiento acerca de mi mismo y de las energ&iacute;as que me afectar&aacute;n en el transcurso de mi vida tendré la posibilidad de ser m&aacute;s libre, al aprovechar las posibilidades latentes. Al conocer por ejemplo la posici&oacute;n de mi luna natal, veré bajo qué predisposiciones subconscientes tiendo a reaccionar, cu&aacute;les son mis h&aacute;bitos emocionales, o mecanismos regresivos… y luego, lo m&aacute;s importante, tendré la posibilidad de modificarlos a través del trabajo personal.</p>
