<h2 class="title">La Astrología y los Números</h2>
<div class="social_networks"></div>
<img class="article_image" src="img/articles_miniatures/numeros.jpg"></img>
<?php include('social-networks.php'); ?>

<div>
  <p>Para comprender la relación entre la <strong>Astrología y los números</strong>, hay <strong>dos factores</strong> que debemos tener en cuenta: <strong>primero</strong> la  <strong>necesidad natural</strong> en el hombre de <strong>buscar un saber</strong>, tanto para predecir lo que le sucederá como para comprender su naturaleza más profunda, su verdadera esencia  y el sentido de su existencia.</p>
  <p><strong>Segundo</strong>, que existen <strong>conocimientos muy antiguos</strong> que satisfacen estas inquietudes y mucho más. Por ejemplo <strong>en la Antigüedad, en Grecia</strong>, se enseñaban  los llamados <strong>“Misterios Mayores”</strong>, donde ciencias muy ricas y complejas como la <strong>Astrología</strong> eran reservadas a un número menor de gente, y luego los <strong>“Misterios Menores”</strong>, como la <strong>Numerología</strong>, donde el saber interior del ser humano se transmitía en forma más popular. Lo interesante es que todos accedían a <strong>una guía psicológica y espiritual</strong>, de uno u otro modo.</p>
  <p>Ahora bien, más allá del uso diario y corriente de los números, tenemos que verlos aquí como <strong>Arquetipos</strong> que ordenan, son elementos universales y como tales, tienen una potencia vinculada en <strong>lo exterior</strong> a determinados flujos cósmicos, fuerzas, planetas, colores, sonidos, metales, elementos químicos, figuras geométricas, frecuencias vibratorias, etc., . Y en <strong>nuestro interior</strong>, asociada a ciertos centros vitales, procesos orgánicos, estados emocionales, etc.</p>
  <p>Así como los números nos sirven de lazo entre lo que viene de fuera y lo que está dentro; la Astrología estudia los principios y leyes que rigen estas dos caras de una misma moneda, presentes en todo lo que existe. Lo que sucede en el cielo, se sincroniza con lo que nos toca vivir.; sea un aprendizaje en lo personal, social o a nivel mundial.</p>
  <p><strong>Repasemos brevemente el lenguaje astrológico básico:</strong> Las <strong>12 Casas</strong> representan los <strong>campos de la experiencia</strong> donde las energías concretas se expresan más fácilmente y donde el individuo se enfrenta a ellas de la manera más directa (EJ: Casa 4 el hogar, la familia). Los <strong>signos</strong> son los <strong>modos de energía</strong>, por ejemplo no es lo mismo la cualidad de Libra con su diplomacia, que la de  Aries con su impulsividad y vigor. Y por último, los <strong>planetas</strong>, son los encargados de <strong>dinamizar la energía, regulan el flujo</strong>. En la carta natal de una persona, hablan de sus funciones psicológicas; por ejemplo Mercurio la inteligencia, su forma de comunicación; la Luna sobre sus emociones. Para los antiguos eran deidades: Venus, la diosa del amor o Saturno el Dios del Tiempo.</p>
  <p><strong>Aclarado esto, recorramos los nueve números y sus analogías</strong></p>
  <p><strong>UNO</strong>: El inicio, la mónada, la unidad. <strong>Se relaciona con el Sol</strong>. En el hombre está asociado el Plexo cardíaco, el corazón, las ideas de firmeza, originalidad, voluntad, iniciativa. Lo masculino.</p>
  <p><strong>DOS:</strong> La dualidad, sensibilidad. <strong>Asociado  a la Luna</strong> y a lo linfático, el estómago, al sentido del gusto, los principios de asociación, adaptación, pasividad y domesticidad. Lo femenino.</p>
  <p><strong>TRES:</strong> La tríada, en la creación el principio de transmutación, manifestación, renovación.  <strong>El planeta es Júpiter</strong>. Vinculado al hígado, órgano encargado de más de 200 funciones en nuestro organismo. La tensión muscular en el cuerpo. A las ideas de expansión, al buen ánimo.</p>
  <p><strong>CUATRO:</strong> Principio de concreción, realidad y permanencia.  Se refiere en el cuerpo al fluido nervioso, la acción de las hormonas. <strong>El planeta relacionado es Urano</strong>, que en Astrología es quien rompe las estructuras para innovar. La inteligencia intuitiva.</p>
  <p><strong>CINCO:</strong> principio de lo andrógino, de lo que es en sí mismo masculino y femenino. <strong>Planeta: Mercurio</strong>. En el hombre está asociado al sistema nervioso, la acción de la bilis, las ideas ingeniosas, la persuasión, investigación, selección y comprensión.</p>
  <p><strong>SEIS:</strong> principio de reposo y movimiento. <strong>Se vincula a  Venus</strong> y al plexo sacro, el sistema glandular. Es lo afectivo, lo que nos relaciona, la reciprocidad, fertilidad.</p>
  <p><strong>SIETE:</strong> principio de tiempo y espacio, de lo que resume en sí mismo lo material pero es la causa que opera más allá de eso. <strong>Su planeta es Neptuno</strong>. Relacionado a la espiritualidad, lo que está más allá, las ansias de vida trascendente.</p>
  <p><strong>OCHO:</strong> en la creación principio de evolución e involución, de la luz y la sombra. <strong>Su planeta es Saturno</strong>. Tiene que ver con los huesos, la columna vertebral. Las ideas que requieren cálculo, cooperación, moderación y repartición en justicia.</p>
  <p><strong>NUEVE:</strong> en la creación relación de comunión entre el pensador, el pensamiento y lo pensado. <strong>El planeta es Marte.</strong> Se asocia  al Plexo coronal, la cabeza. Rige la sangre, proceso de la combustión. Se relaciona al coraje, la iniciativa y la espontaneidad.</p>
  <p> </p>
  <p>Fuente: Libro “La Cábala de Predicción” de Jesús Iglesias Janeiro.</p>
</div>
