<h2 class="title">The Astrological Theory of Personality</h2>
<div class="social_networks"></div>
<img class="article_image" src="img/articles_miniatures/personalidad.jpg" alt="Illustration of Personality"></img>
<?php include('social-networks.php'); ?>

<p>In <strong>psychological astrology</strong>, planets can be divided into three groups. The first group consists of basic personal factors: Sun, Moon, Mercury, Venus, and Mars. These <strong>planets</strong> show which forces we can consciously direct or modify, to some extent. These planets characterize the most evident traits of <strong>personality</strong> and the individual's strongest impulses. Each experiences a sense of <em>individuality and self-identity</em> (<strong>Sun</strong>), a way of reacting spontaneously based on <em>conditioned responses</em> (<strong>Moon</strong>), an aptitude for reasoning and exchanging <em>thoughts</em> with others (<strong>Mercury</strong>), a need and capacity for <em>love and close relationships</em> (<strong>Venus</strong>), and a tendency toward <em>action, self-confidence, and sexual experience</em> (<strong>Mars</strong>).</p>
<p>Underlying these basic personal factors are the deeper <em>motivational and collective factors</em>, symbolized by Jupiter and Saturn. Their collective significance refers to their impact on how one wants to <em>participate in the world in general</em> and in relation to <em>social activities</em>. These planets represent the deepest currents of stability, tradition, and security (<strong>Saturn</strong>), and future aspirations, a sense of adventure, boldness, and personal growth (<strong>Jupiter</strong>).</p>
<p>The third group is comprised of <strong>Uranus, Neptune, and Pluto</strong>. This group symbolizes the deepest sources of change in life, <em>transcendent dimensions of experience</em>, and the subtle energies with which we are attuned. These forces affect our most conscious faculties through inspiration, perceptual flashes, intuition, innate knowledge not learned through intellect, an impulse to merge into a greater whole, and a strong drive toward refinement of our deeper nature. When these energies come into play, <em>old life patterns are broken</em> and change rapidly. These three planets together can be said to refer to transpersonal factors and transformative energies within each of us.</p>
<p>Considered as components of a single <strong>total energy system</strong>, these three groups of planets provide the practitioner with a complete and extensive theory of human personality and <strong>psychological functioning</strong>, a reference structure based on the need for security, love, and creativity, as well as the constant impulses toward self-realization, change, growth, and transcendence. When we focus on the individual and life in general at the same level at which the <em><strong>essential energies of life</strong></em> operate, we can begin to see <strong>the mind and body</strong> as interacting and living <em>energy fields</em> rather than rigid mechanical contrivances. Such an understanding of the total human can open the door to the development of a new kind of astrology, a science based on the laws of life.</p>
