<h2 class="title">La Teoría Astrológica de la Personalidad</h2>
<div class="social_networks"></div>
<img class="article_image" src="img/articles_miniatures/personalidad.jpg"></img>
<?php include('social-networks.php'); ?>

<p>En la <strong>astrología psicológica</strong>, los planetas pueden dividirse en tres grupos. El primer grupo consiste en los factores personales básicos: Sol, Luna, Mercurio, Venus y Marte. Estos <strong>planetas</strong> muestran qué fuerzas podremos dirigir o modificar conscientemente, hasta cierto punto. Estos planetas caracterizan los rasgos más evidentes de la <strong>personalidad</strong> y los impulsos más fuertes del individuo. Cada cual experimenta un sentido de <em>la individualidad y la autoidentidad</em> (<strong>Sol</strong>), un modo de reaccionar espontáneamente, basado en <em>respuestas condicionadas</em> (<strong>Luna</strong>), una aptitud para razonar e intercambiar <em>pensamientos</em> con los demás (<strong>Mercurio</strong>), una necesidad y una capacidad de<em> amor y estrecha relación</em> (<strong>Venus</strong>), y una tendencia hacia la <em>acción, la fe en si mismo y la experiencia sexual</em> (<strong>Marte</strong>).</p>
<p>Subyacentes en estos factores personales básicos están los más profundos <em>factores motivacionales y colectivos</em>, simbolizados por Júpiter y Saturno. Su significación colectiva se refiere a su impacto sobre cómo uno quiere <em>participar del mundo en general</em> y en relación con las <em>actividades sociales</em>. Estos planetas representan las corrientes más profundas de la estabilidad, la tradición y la seguridad (<strong>Saturno</strong>), y las aspiraciones futuras, sentido de la aventura, osadía y crecimiento personal (<strong>Júpiter</strong>).</p>
<p>El tercer grupo es comprendido por <strong>Urano, Neptuno y Plutón</strong>. Este grupo simboliza las fuentes más profundas del cambio en la vida, las <em>dimensiones trascendentes de la experiencia</em> y las energías más sutiles con las que estamos armonizados. Estas fuerzas afectan nuestras facultades más conscientes a través de la inspiración, destellos perceptivos, intuición, conocimiento innato no aprendido a través del intelecto, un impulso a fundirse en una totalidad mayor, y un fuerte impulso hacia un refinamiento de nuestra naturaleza más profunda. Cuando estas energías entran en juego, se <em>rompen las viejas pautas de vida</em> y cambian rápidamente. Estos tres planetas juntos puede decirse que se refieren a factores trans personales y a las energías transformativas dentro de la vida de cada uno de nosotros.</p>
<p>Considerados como los componentes de un solo <strong>sistema total de energía</strong>, estos tres grupos de planetas suministran al profesional una teoría completa y vasta de la personalidad humana y del <strong>funcionamiento psicológico</strong>, una estructura de referencia fundada tanto en la necesidad de seguridad, amor y creatividad como en los constantes impulsos hacia la autorrealización, el cambio, el crecimiento y la trascendencia. Cuando enfocamos al individuo y a la vida en general en el mismo nivel en que operan las <em><strong>energías esenciales de la vida</strong></em>, podemos empezar a ver <strong>la mente y el cuerpo</strong> como <em>campos energéticos </em>interactuantes y vivos más que como rígidos ingenios mecánicos. tal comprensión del hombre total puede abrir la puerta hacia el desarrollo de un nuevo género de astrología, una ciencia que se basa en las leyes de la vida.</p>
