<h2 class="title">&iquest;Qu&eacute; son los tr&aacute;nsitos&quest;</h2>
<div class="social_networks"></div>
<img class="article_image" src="img/articles_miniatures/que-son-los-transitos.jpg"></img>
<?php include('social-networks.php'); ?>

<p>Un astrólogo puede estudiar la <strong>carta natal</strong> de una persona, sus cualidades, sus posibilidades realizadoras en diferentes ámbitos o sus tendencias negativas. Está claro que la Carta Natal representa nuestra <strong>estructura psíquica</strong>, y que no cambia. Pero, ¿por qué nosotros tenemos la posibilidad de ir <strong>cambiando</strong> a lo largo de nuestras vidas? ¿por qué vivenciamos marcados períodos de <strong>crecimiento</strong> y otros de <strong>frustraciones y dificultades</strong>? ¿qué es lo que determina estos <strong>ciclos</strong> en nuestras vidas?</p>
 
<p>La astrología, a través de un estudio serio, puede ayudar a la persona siguiéndola en el tiempo con varios métodos de pronóstico y predicción como son las <strong>progresiones, las direcciones, las revoluciones solares </strong>(carta anual) y las <strong>revoluciones lunares</strong> (carta mensual).</p>

<p>El sistema más sencillo es el de los <strong>Tránsitos</strong> de los planetas sobre la propia carta natal. La carta natal en realidad es una <strong>foto fija del cielo</strong> en el momento y lugar exactos del nacimiento. Los astros siguen su camino, a esto se le llama <i>“tránsito”</i>. Un Tránsito es el <strong>movimiento</strong> de un planeta a través del zodiaco día a día, semana tras semana, año tras año. Cada planeta, en su recorrido, va pasando por diferentes signos formando <strong>aspectos</strong> con los planetas natales u otros puntos importantes de la carta natal, o simplemente transitando por una <strong>casa</strong> o sector vacío de nuestra carta.</p>

<p>Su período de paso por cada casa dependerá del planeta en cuestión, ya que cada uno va a su <strong>ritmo y velocidad</strong>, y tarda un determinado espacio de tiempo. Así pues algunos planetas tardan más que otros en su recorrido, por ejemplo <strong>Plutón</strong> puede estar <strong>20 años</strong> en un mismo signo. La <strong>Luna</strong> en cambio, estará sólo <strong>2 días y unas horas</strong> aproximadamente en cada signo del zodiaco. Si voy a tener durante 3 años por ejemplo un tránsito de <strong>Plutón</strong> o <strong>Neptuno</strong> será bueno saberlo, anticiparme, prepararme y aprovechar para hacer los cambios necesarios. Esta <strong>actitud</strong> será mucho más <strong>positiva</strong> que resistirme, negarme, angustiarme o frustrarme frente a proyectos que no fructifican debido a que sencillamente <strong>no es el momento propicio</strong> para poner mis energías en eso. Pero sí podré poner mis energías en tantas otras cosas en las que seguramente podré <strong>desarrollarme y crecer</strong> de otro modo.</p>

<p>Allí reside la vital importancia de conocer los transitos de los planetas sobre mi carta natal. Los tránsitos más importantes son los de los planetas más lentos, por tener unos efectos más duraderos: <strong>Plutón, Neptuno, Urano, Saturno y Júpiter</strong>. 	Si querés conocer tus tránsitos para este año, es decir tus <strong>ciclos de cambio y crecimiento</strong>, solicitá tu carta natal y tu Entrevista Personal.</p>